"""initial_schema

Revision ID: 031b54f51af7
Revises: 
Create Date: 2026-09-12 11:56:22.797641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user


# revision identifiers, used by Alembic.
revision: str = '031b54f51af7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_by', app.models.user.GUID(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('assessments',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.user.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('per_question_time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('fast_response_threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('enable_speed_adaptive', sa.Boolean(), nullable=False),
    sa.Column('max_question_count', sa.Integer(), nullable=False),
    sa.Column('promotion_threshold', sa.Integer(), nullable=False),
    sa.Column('demotion_threshold', sa.Integer(), nullable=False),
    sa.Column('max_violations', sa.Integer(), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('promotion_rules', sa.JSON(), nullable=False),
    sa.Column('ban_on_violation_breach', sa.Boolean(), nullable=False),
    sa.Column('device_switch_as_violation', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('config_locked', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'closed')", name='ck_assessment_status'),
    sa.CheckConstraint('demotion_threshold >= 1', name='ck_assessment_demotion_threshold'),
    sa.CheckConstraint('fast_response_threshold_seconds >= 1', name='ck_assessment_fast_response_threshold'),
    sa.CheckConstraint('max_question_count >= 1', name='ck_assessment_max_question_count'),
    sa.CheckConstraint('max_violations >= 1', name='ck_assessment_max_violations'),
    sa.CheckConstraint('per_question_time_limit_seconds IS NULL OR per_question_time_limit_seconds >= 1', name='ck_assessment_per_q_limit'),
    sa.CheckConstraint('promotion_threshold >= 1', name='ck_assessment_promotion_threshold'),
    sa.CheckConstraint('time_limit_seconds >= 1', name='ck_assessment_time_limit'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('actor_user_id', app.models.user.GUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', app.models.user.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_actor', ['actor_user_id'], unique=False)
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)

    op.create_table('course_materials',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.user.GUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_materials_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('token_id', sa.String(length=255), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_id'), ['token_id'], unique=True)

    op.create_table('ai_generation_jobs',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('material_id', app.models.user.GUID(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('valid_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'processing', 'completed', 'failed')", name='ck_ai_job_status'),
    sa.ForeignKeyConstraint(['material_id'], ['course_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generation_jobs', schema=None) as batch_op:
        batch_op.create_index('idx_ai_jobs_material', ['material_id'], unique=False)
        batch_op.create_index('idx_ai_jobs_status', ['status'], unique=False)

    op.create_table('assessment_bans',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('assessment_id', app.models.user.GUID(), nullable=False),
    sa.Column('student_id', app.models.user.GUID(), nullable=False),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('banned_by', app.models.user.GUID(), nullable=True),
    sa.Column('ban_source', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', app.models.user.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_bans', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_bans_lookup', ['assessment_id', 'student_id'], unique=False)
        batch_op.create_index('uq_active_assessment_ban', ['assessment_id', 'student_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))

    op.create_table('questions',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('material_id', app.models.user.GUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('source_chunk_ref', sa.String(length=255), nullable=False),
    sa.Column('is_duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['course_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_material_id'), ['material_id'], unique=False)

    op.create_table('assessment_questions',
    sa.Column('assessment_id', app.models.user.GUID(), nullable=False),
    sa.Column('question_id', app.models.user.GUID(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('assessment_id', 'question_id', name='pk_assessment_questions')
    )
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.create_index('idx_assessment_questions_aid', ['assessment_id'], unique=False)
        batch_op.create_index('idx_assessment_questions_diff', ['assessment_id', 'difficulty'], unique=False)
        batch_op.create_index('idx_assessment_questions_qid', ['question_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('assessment_id', app.models.user.GUID(), nullable=False),
    sa.Column('student_id', app.models.user.GUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('highest_difficulty_reached', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('completion_reason', sa.String(length=64), nullable=True),
    sa.Column('consent_ack_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_device_id', sa.String(length=255), nullable=False),
    sa.Column('promotion_counter', sa.Integer(), nullable=False),
    sa.Column('demotion_counter', sa.Integer(), nullable=False),
    sa.Column('current_question_id', app.models.user.GUID(), nullable=True),
    sa.Column('current_question_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("completion_reason IS NULL OR completion_reason IN ('student_submitted', 'time_expired', 'violation_threshold', 'no_questions_remaining', 'max_questions_reached', 'teacher_terminated', 'banned', 'system_error', 'disconnect_timeout')", name='ck_attempt_completion_reason'),
    sa.CheckConstraint("status IN ('in_progress', 'submitted', 'terminated', 'disconnected')", name='ck_attempt_status'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index('idx_attempts_assessment', ['assessment_id'], unique=False)
        batch_op.create_index('idx_attempts_lookup', ['assessment_id', 'student_id', 'status'], unique=False)
        batch_op.create_index('idx_attempts_status', ['status'], unique=False)
        batch_op.create_index('idx_attempts_student', ['student_id'], unique=False)

    op.create_table('attempt_answers',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('attempt_id', app.models.user.GUID(), nullable=False),
    sa.Column('question_id', app.models.user.GUID(), nullable=False),
    sa.Column('selected_option_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('difficulty_at_time', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_answer_question')
    )
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.create_index('idx_attempt_answers_attempt', ['attempt_id'], unique=False)

    op.create_table('attempt_question_servings',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('attempt_id', app.models.user.GUID(), nullable=False),
    sa.Column('question_id', app.models.user.GUID(), nullable=False),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('sequence_number >= 1', name='ck_serving_sequence_positive'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question_serving'),
    sa.UniqueConstraint('attempt_id', 'sequence_number', name='uq_attempt_sequence_serving')
    )
    with op.batch_alter_table('attempt_question_servings', schema=None) as batch_op:
        batch_op.create_index('idx_servings_attempt', ['attempt_id'], unique=False)
        batch_op.create_index('idx_servings_question', ['question_id'], unique=False)

    op.create_table('device_switch_log',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('attempt_id', app.models.user.GUID(), nullable=False),
    sa.Column('previous_device_id', sa.String(length=255), nullable=False),
    sa.Column('new_device_id', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_switch_log', schema=None) as batch_op:
        batch_op.create_index('idx_device_switch_attempt', ['attempt_id'], unique=False)

    op.create_table('violations',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('attempt_id', app.models.user.GUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.CheckConstraint("type IN ('tab_switch', 'window_blur', 'copy', 'paste', 'cut', 'screenshot_attempt', 'device_switch')", name='ck_violation_type'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index('idx_violations_attempt', ['attempt_id'], unique=False)
        batch_op.create_index('idx_violations_occurred_at', ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index('idx_violations_occurred_at')
        batch_op.drop_index('idx_violations_attempt')

    op.drop_table('violations')
    with op.batch_alter_table('device_switch_log', schema=None) as batch_op:
        batch_op.drop_index('idx_device_switch_attempt')

    op.drop_table('device_switch_log')
    with op.batch_alter_table('attempt_question_servings', schema=None) as batch_op:
        batch_op.drop_index('idx_servings_question')
        batch_op.drop_index('idx_servings_attempt')

    op.drop_table('attempt_question_servings')
    with op.batch_alter_table('attempt_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_attempt_answers_attempt')

    op.drop_table('attempt_answers')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('idx_attempts_student')
        batch_op.drop_index('idx_attempts_status')
        batch_op.drop_index('idx_attempts_lookup')
        batch_op.drop_index('idx_attempts_assessment')

    op.drop_table('attempts')
    with op.batch_alter_table('assessment_questions', schema=None) as batch_op:
        batch_op.drop_index('idx_assessment_questions_qid')
        batch_op.drop_index('idx_assessment_questions_diff')
        batch_op.drop_index('idx_assessment_questions_aid')

    op.drop_table('assessment_questions')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_material_id'))

    op.drop_table('questions')
    with op.batch_alter_table('assessment_bans', schema=None) as batch_op:
        batch_op.drop_index('uq_active_assessment_ban', postgresql_where=sa.text('revoked_at IS NULL'), sqlite_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index('idx_assessment_bans_lookup')

    op.drop_table('assessment_bans')
    with op.batch_alter_table('ai_generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_ai_jobs_status')
        batch_op.drop_index('idx_ai_jobs_material')

    op.drop_table('ai_generation_jobs')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_id'))
        batch_op.drop_index('idx_refresh_tokens_user')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('course_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_materials_teacher_id'))

    op.drop_table('course_materials')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_actor')
        batch_op.drop_index('idx_audit_action')

    op.drop_table('audit_log')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_teacher_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
